
[build]
  publish = "dist"
  command = "bun run build"

# Instead of trying to disable the CommandBar plugin, let's completely remove it
# and only keep the Cloudflare plugin

# Keep other plugins
[[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"
